<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:28:11 and allows to alter the behaviour of the 'Invitation' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Guestlist;

use Honeybee\Domain\Guestlist\Base;

/**
 * The InvitationModule class reflects the declared structure of the 'Invitation' entity.
 * It holds the meta data necessary to manage/initiate 'InvitationDocument' lifecycles.
 */
class InvitationModule extends Base\InvitationModule
{

}
