<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:26:52 and allows to alter the behaviour of 'Event' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Event;

use Honeybee\Domain\Event\Base;

/**
 * Holds the structure definition for Event documents.
 */
class EventDocument extends Base\EventDocument
{

}
