<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:26:52 and allows to alter the behaviour of the 'Event' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Event;

use Honeybee\Domain\Event\Base;

/**
 * The EventModule class reflects the declared structure of the 'Event' entity.
 * It holds the meta data necessary to manage/initiate 'EventDocument' lifecycles.
 */
class EventModule extends Base\EventModule
{

}
