<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:26:52 and allows to alter the behaviour of 'PluginResult' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Event;

use Honeybee\Domain\Event\Base;

/**
 * A PluginResult reflects a state resulting from executing a workflow plugin.
 */
class PluginResultDocument extends Base\PluginResultDocument
{

}
