<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-17 18:23:26 and allows to alter the behaviour of 'WorkflowTicket' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Event;

use Honeybee\Domain\Event\Base;

/**
 * The WorkflowTicket aggregate holds reflects the current state of an documents workflow state.
 */
class WorkflowTicketDocument extends Base\WorkflowTicketDocument
{

}
