<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:37:22 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Guest' module,
then the 'GuestModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Guest\Base;

use Dat0r\Core\Field\AggregateField;
use Dat0r\Core\Field\KeyValueField;
use Dat0r\Core\Field\TextField;
use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Guest'' module skeleton.
 */
abstract class GuestModule extends Dat0r\Module
{
    /**
     * Creates a new GuestModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'Guest',
            array(
                TextField::create(
                    'firstname',
                    array()
                ),
                TextField::create(
                    'lastname',
                    array()
                ),
                TextField::create(
                    'fullname',
                    array()
                ),
                KeyValueField::create(
                    'meta',
                    array(
                        'constraints' => array(
                            'value_type' => 'dynamic',
                        ),
                    )
                ),
                AggregateField::create(
                    'workflowTicket',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Guest\\WorkflowTicketModule',
                        ),
                    )
                ),
            ),
            array(
                'prefix' => 'guest',
                'identifier_field' => 'identifier',
                'slugPattern' => 'guest-{shortId}',
            )
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Guest\\GuestDocument';
    }
}
