<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:37:22 and allows to alter the behaviour of the 'Guest' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Guest;

use Honeybee\Domain\Guest\Base;

/**
 * The GuestModule class reflects the declared structure of the 'Guest' entity.
 * It holds the meta data necessary to manage/initiate 'GuestDocument' lifecycles.
 */
class GuestModule extends Base\GuestModule
{

}
