<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:28:11 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Guestlist' documents,
then the 'GuestlistDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Guestlist\Base;

use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Guestlist' document skeleton.
 */
abstract class GuestlistDocument extends Dat0r\Document
{
    /**
     * Returns an 'Guestlist' document's title.
     *
     * @return 
     */
    public function getTitle()
    {
        return $this->getValue('title');
    }

    /**
     * Sets an 'Guestlist' document's title.
     *
     * @param  $title
     */
    public function setTitle($title)
    {
        $this->setValue('title', $title);
    }

    /**
     * Returns an 'Guestlist' document's description.
     *
     * @return 
     */
    public function getDescription()
    {
        return $this->getValue('description');
    }

    /**
     * Sets an 'Guestlist' document's description.
     *
     * @param  $description
     */
    public function setDescription($description)
    {
        $this->setValue('description', $description);
    }

    /**
     * Returns an 'Guestlist' document's invitations.
     *
     * @return 
     */
    public function getInvitations()
    {
        return $this->getValue('invitations');
    }

    /**
     * Sets an 'Guestlist' document's invitations.
     *
     * @param  $invitations
     */
    public function setInvitations($invitations)
    {
        $this->setValue('invitations', $invitations);
    }

    /**
     * Returns an 'Guestlist' document's meta.
     *
     * @return 
     */
    public function getMeta()
    {
        return $this->getValue('meta');
    }

    /**
     * Sets an 'Guestlist' document's meta.
     *
     * @param  $meta
     */
    public function setMeta($meta)
    {
        $this->setValue('meta', $meta);
    }

    /**
     * Returns an 'Guestlist' document's workflowTicket.
     *
     * @return 
     */
    public function getWorkflowTicket()
    {
        return $this->getValue('workflowTicket');
    }

    /**
     * Sets an 'Guestlist' document's workflowTicket.
     *
     * @param  $workflowTicket
     */
    public function setWorkflowTicket($workflowTicket)
    {
        $this->setValue('workflowTicket', $workflowTicket);
    }
}
