<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:28:11 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Invitation' documents,
then the 'InvitationDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Guestlist\Base;

use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Invitation' document skeleton.
 */
abstract class InvitationDocument extends Dat0r\BaseDocument
{
    /**
     * Returns an 'Invitation' document's guest.
     *
     * @return 
     */
    public function getGuest()
    {
        return $this->getValue('guest');
    }

    /**
     * Sets an 'Invitation' document's guest.
     *
     * @param  $guest
     */
    public function setGuest($guest)
    {
        $this->setValue('guest', $guest);
    }

    /**
     * Returns an 'Invitation' document's extra_guests.
     *
     * @return 
     */
    public function getExtraGuests()
    {
        return $this->getValue('extra_guests');
    }

    /**
     * Sets an 'Invitation' document's extra_guests.
     *
     * @param  $extra_guests
     */
    public function setExtraGuests($extra_guests)
    {
        $this->setValue('extra_guests', $extra_guests);
    }
}
