<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-12-16 23:28:11 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Invitation' module,
then the 'InvitationModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Guestlist\Base;

use Dat0r\Core\Field\IntegerField;
use Dat0r\Core\Field\ReferenceField;
use Dat0r\Core\Module;

/**
 * Serves as the base class to the 'Invitation'' module skeleton.
 */
abstract class InvitationModule extends Module\AggregateModule
{
    /**
     * Creates a new InvitationModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'Invitation',
            array(
                ReferenceField::create(
                    'guest',
                    array(
                        'enable_inline_create' => true,
                        'max' => 1,
                        'references' => array(
                            array(
                                'module' => '\\Honeybee\\Domain\\Guest\\GuestModule',
                                'identity_field' => 'identifier',
                                'display_field' => 'fullname',
                            ),
                        ),
                    )
                ),
                IntegerField::create(
                    'extra_guests',
                    array()
                ),
            ),
            array()
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Guestlist\\InvitationDocument';
    }
}
